# Generated by Django 4.1.1 on 2022-10-09 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=256)),
                ('cpf_cnpj', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=19)),
                ('responsavel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Responsaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=256)),
                ('cpf_cnpj', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Transportadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=256)),
                ('cpf_cnpj', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=19)),
                ('veiculo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=8)),
                ('capacidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(choices=[('E', 'Escolas'), ('R', 'Responsaveis'), ('T', 'Transportadores')], max_length=1)),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=256)),
                ('cpf_cnpj', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=19)),
                ('nutri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=256)),
                ('cpf_cnpj', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=19)),
                ('responsaveis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.responsaveis')),
            ],
        ),
    ]
